services:
  gl-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1435:1433"
    container_name: gl-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BigPass_1234
    restart: always

  glowingsystem_backend:
    depends_on:
      - gl-db
    build:
      context: ./GlowingSystem.Backend
    container_name: gl_backend
    ports:
      - "5119:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000

  glowingsystem_frontend:
    build:
      context: ./GlowingSystem.Frontend
    image: emstd/glowingsystem_frontend:runtime
    container_name: gl_frontend
    ports:
      - "8080:4173"